### ISSUE TITLE
Fix login modal, and require login to make edits

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-iD#14]
I believe, @olafveerman, that you said this was an SSL issue?

**Comment by olafveerman** [comment]
Haven't look into it much, but I believe it has to do with loading the OSM Oauth over http instead of https

**Comment by mileswwatkins** [comment]
Noting that this is the specific issue we're hitting:

<img width="1399" alt="screen shot 2017-07-25 at 17 13 22" src="https://user-images.githubusercontent.com/4959135/28594072-9c779a7c-715c-11e7-85ee-a96cd518aac9.png">

**Comment by mileswwatkins** [comment]
https://github.com/orma/openroads-vn-iD/commit/a258011d4177441432c446397f27d3baa8d4aa58
